### ISSUE TITLE
1.4.0 new zones issue

### ISSUE THREAD

**Issue by kyle4269** [ljmerza/frigate_plate_recognizer#11]
@ljmerza 
Trying out your new release and encountered the following error.

config:
```
frigate:
  frigate_url: http://****:5000
  mqtt_server: ************
  mqtt_auth: true
  mqtt_username: mqtt
  mqtt_password: ****
  main_topic: frigate
  return_topic: plate_recognizer
  camera:
    - test
  zones:
    - Lp
  min_score: .65
plate_recognizer:
  token: ************
  regions:
    - us-ri
logger_level: INFO
```

```
frigate_plate_test  | 2023-11-14 20:02:55,250 - __main__ - INFO - MQTT Connected
frigate_plate_test  | Traceback (most recent call last):
frigate_plate_test  |   File "//./index.py", line 301, in <module>
frigate_plate_test  |     main()
frigate_plate_test  |   File "//./index.py", line 297, in main
frigate_plate_test  |     run_mqtt_client()
frigate_plate_test  |   File "//./index.py", line 260, in run_mqtt_client
frigate_plate_test  |     mqtt_client.loop_forever()
frigate_plate_test  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
frigate_plate_test  |     rc = self._loop(timeout)
frigate_plate_test  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
frigate_plate_test  |     rc = self.loop_read()
frigate_plate_test  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
frigate_plate_test  |     rc = self._packet_read()
frigate_plate_test  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
frigate_plate_test  |     rc = self._packet_handle()
frigate_plate_test  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
frigate_plate_test  |     return self._handle_publish()
frigate_plate_test  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
frigate_plate_test  |     self._handle_on_message(message)
frigate_plate_test  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
frigate_plate_test  |     on_message(self, self._userdata, message)
frigate_plate_test  |   File "//./index.py", line 126, in on_message
frigate_plate_test  |     matching_zone = any(value in after_data['zones'] for value in config_zones)
frigate_plate_test  |   File "//./index.py", line 126, in <genexpr>
frigate_plate_test  |     matching_zone = any(value in after_data['zones'] for value in config_zones)
frigate_plate_test  | KeyError: 'zones'
frigate_plate_test exited with code 0
```
