### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './config/config.yml'

### ISSUE THREAD

**Issue by gadget-man** [ljmerza/frigate_plate_recognizer#19]
I'm trying to launch this on my Synology NAS using docker compose (I have loads of other containers working fine)

I've created a frigate-plate-recognizer folder inside /volume1/docker, together with a /config/config.yml file as per the instructions.

When I call `sudo docker-compose up` I get the following error:

frigate_plate_recognizer  | Traceback (most recent call last):
frigate_plate_recognizer  |   File "/usr/src/app/./index.py", line 357, in <module>
frigate_plate_recognizer  |     main()
frigate_plate_recognizer  |   File "/usr/src/app/./index.py", line 337, in main
frigate_plate_recognizer  |     load_config()
frigate_plate_recognizer  |   File "/usr/src/app/./index.py", line 287, in load_config
frigate_plate_recognizer  |     with open(CONFIG_PATH, 'r') as config_file:
frigate_plate_recognizer  | FileNotFoundError: [Errno 2] No such file or directory: './config/config.yml'

If I delete the /config folder (and contents), I get a different error that the config folder can't be found, so I know that the mapping is working. Here's my docker-compose.yaml:

services:
  frigate_plate_recognizer:
    image: lmerza/frigate_plate_recognizer:latest
    container_name: frigate_plate_recognizer
    volumes:
      - /volume1/docker/frigate-plate-recognizer/config:/config
    restart: unless-stopped
    environment:
      - TZ=Europe/London

Am I doing something obviously wrong, or is there a bug in where it's trying to read my config.yml file from?

**Comment by gadget-man** [comment]
I worked it out: for anyone else trying this on Synology Diskstation, you need to set the volumes to point to 
`/usr/src/app/config` not just `/config`

**Comment by ljmerza** [comment]
Thanks for leaving the answer.

**Comment by DrSpaldo** [comment]
Thanks for posting your answer @gadget-man . I am running Unraid and just wanted to post that I had a very similar experience. My docker compose (via Stack) for Unraid was as follows:

```
services:
  frigate_plate_recognizer:
    image: lmerza/frigate_plate_recognizer:latest
    container_name: frigate_plate_recognizer
    volumes:
      - /mnt/user/appdata/plate-recognizer:/usr/src/app/config
    restart: unless-stopped
    environment:
      - TZ=Australia/Brisbane
```
