### ISSUE TITLE
Container has stopped working after last update on 07-Dec with error No such file or directory: './config/config.yml'

### ISSUE THREAD

**Issue by heisenberg2980** [ljmerza/frigate_plate_recognizer#20]
I am using "latest" in my docker-compose file and after the latest update on 7th December my instance has stopped working and it is returning this error: "FileNotFoundError: [Errno 2] No such file or directory: './config/config.yml'". I have checked the config file exists. Using tag 1.7.1 has solved the issue so the error must be in the last update (1.7.3).

This is the full error:
```
Traceback (most recent call last):
  File "/usr/src/app/./index.py", line 357, in <module>
    main()
  File "/usr/src/app/./index.py", line 337, in main
    load_config()
  File "/usr/src/app/./index.py", line 287, in load_config
    with open(CONFIG_PATH, 'r') as config_file:
FileNotFoundError: [Errno 2] No such file or directory: './config/config.yml'
```

**Comment by kyle4269** [comment]
I believe someone else had the same issue and they fix it by
 "you need to set the volumes to point to
/usr/src/app/config not just /config"

**Comment by heisenberg2980** [comment]
@ljmerza this issue is still happening (I reverted my instance to the previous version to avoid it), will it be fixed in the next release?

**Comment by ljmerza** [comment]
What's your config look like? I'm not running into this issue

**Comment by heisenberg2980** [comment]
This is my docker-compose.yaml file:
```
services:
  frigate_plate_recognizer:
    image: lmerza/frigate_plate_recognizer:1.7.1
    container_name: frigate_plate_recognizer
    volumes:
      - ./config:/config
    restart: unless-stopped
    environment:
      - TZ=Europe/London
```

**Comment by ljmerza** [comment]
i mean your config.yml file?

**Comment by heisenberg2980** [comment]
This is my config file:
```
frigate:
  frigate_url: http://192.168.0.209:5000
  mqtt_server: 192.168.0.253
  mqtt_auth: true
  mqtt_username: **removed**
  mqtt_password: **removed**
  main_topic: frigate
  return_topic: plate_recognizer
  camera:
    - dahua_5
    - dahua_1
  min_score: .8
plate_recognizer:
  token: **removed**
  regions:
    - gb
logger_level: INFO
#logger_level: DEBUG
```
