### ISSUE TITLE
Best camera for detecting license plates on slow but moving cars

### ISSUE THREAD

**Issue by atv2016** [ljmerza/frigate_plate_recognizer#44]
I have a fairly good view on a road leading up to my house, maybe a 100 meters or so.
What camera would everyone suggest to use? 1080P doesn't cut it, I only get a recognition when it's about 6 meters away and pulling in my driveway.

4K ? 8K? any brands or types you have good results with would be appreciated. Or do I need to get a special ANPR camera.

**Comment by kyle4269** [comment]
I'd recommend [this](https://empiretech01.com/products/empiretech-2mp-wdr-ir-bullet-ai-network-bullet-camera-ipc-hfw5241e-z12e?variant=46858538909981). See [this thread](Mini-Review - 5241-Z12E-S2 - Replacement for the 5241-Z12E
 https://ipcamtalk.com/index.php?threads/Mini-Review---5241-Z12E-S2---Replacement-for-the-5241-Z12E.71898/). There is a ton of information on that camera

**Comment by atv2016** [comment]
Cool thanks. PS Would any of these settings in frigate itself make a difference to this integration?
Specifically frames p/s and car minimum window ?

```

        - detect
        - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
      - person
      - dog
      - bicycle
      - cat
      - car
      filters:
        car:
          min_area: 15000

```
