### ISSUE TITLE
Failed to set sublabel. Status code: 404

### ISSUE THREAD

**Issue by tinstep** [ljmerza/frigate_plate_recognizer#64]
I'm having an issue where I cant get a the sub-label set.  This is a new setup and i'm new to Frigate and Codeproject.ai
There are also a couple of things I don't understand. Do I need to add the codeproject URL to the frigate config in frigate itself? - I thought that frigate_plate_recognizer was the glue between the two apps?

```
2024-11-10 13:50:06,210 - __main__ - INFO - Frigate Plate Recognizer Version: 1.8.14
2024-11-10 13:50:06,210 - __main__ - INFO - Using CodeProject.AI API
2024-11-10 13:50:06,210 - __main__ - INFO - Starting MQTT client. Connecting to: 192.168.0.18
2024-11-10 13:50:06,214 - __main__ - INFO - MQTT Connected
2024-11-10 13:50:35,049 - __main__ - INFO - Recognised plate is a Watched Plate: AAZ524
2024-11-10 13:50:35,049 - __main__ - INFO - Storing plate number in database: AAZ524 with score: 0.9950941205024719
2024-11-10 13:50:35,093 - __main__ - ERROR - Failed to set sublabel. Status code: 404
2024-11-10 13:50:35,308 - __main__ - INFO - Saving image with path: /plates/AAZ524_driveway_2024-11-10_13-50.png
```

These are the things I have tried:
1) Using docker internal names to help speed things up. - didn't work
2) Making a bunch of config changes to see what happens - mostly around snapshots.
3) Adding a 6 second sleep (see code below) in the code as per this post: [https://github.com/ljmerza/frigate_plate_recognizer/issues/16]

```
    if watched_plate:
        time.sleep(6)
        message = {
            'plate_number': str(watched_plate).upper(),
            'score': plate_score,
            'frigate_event_id': frigate_event_id,
            'camera_name': after_data['camera'],
            'start_time': formatted_start_time,
            'fuzzy_score': fuzzy_score,
            'original_plate': str(plate_number).upper()
        }
```

Here is my config - any help appreciated :

```
frigate:
  frigate_url: http://frigate:5000
  zones:
    - detection
  mqtt_server: 192.168.0.18
  mqtt_port: 1883 # Optional. Default shown.
  mqtt_username: mqttuser
  mqtt_password: PASSWORDREMOVED
  main_topic: frigate
  return_topic: plate_recognizer
  frigate_plus: false
  save_snapshots: True # Saves a snapshot called [Camera Name]_[timestamp].png
  draw_box: True # Optional - Draws a box around the plate on the snapshot along with the license plate text (Required Frigate plus setting)
  always_save_snapshot: False # Optional - will save a snapshot of every event sent to frigate_plate_recognizer, even if no plate is detected
  watched_plates: #list of plates to watch.
    - AAZ524
    - AAZ 524
    - 1RE9EJ
  fuzzy_match: 0.7 # default is test against plate-recognizer / CP.AI 'candidates' only, but can specify a min score for fuzzy matching if no cand>
  camera:
    - driveway
  objects:
    - car
  min_score: .7
code_project:
  api_url: http://192.168.0.14:32168/v1/image/alpr
logger_level: INFO

```

Frigate 1.14.1 config
```
mqtt:
  enabled: true
  host: 192.168.0.18
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqttuser
  password: mqttpassword
#  bounding_box: True


go2rtc:
  streams:
    driveway:
      - ffmpeg:http://192.168.0.24/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=PASSWORDREMOVED#video=copy#audio=copy#audio=opus
#    drivway_sub:
#      - ffmpeg:http://192.168.0.24/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=PASSWORDREMOVED


cameras:
  driveway:
    snapshots:
      required_zones:
        - driveway
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
#        - path: rtsp://127.0.0.1:8554/driveway_sub
#          input_args: preset-rtsp-restream
#          roles:
#            - detect


    detect:
      enabled: true # <---- disable detection until you have a working camera feed
#      stationary:
        # When set to 1, object detection will run to confirm the object still exists on every frame.
        # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
#        interval: 50
        # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
#        threshold: 50
#      width: 896
#      height: 672
#      fps: 12
    zones:
      detection:
        coordinates: 0,0.037,0,1,0.981,0.99,0.968,0.079
        loitering_time: 0
        inertia: 3
#    review:
#      detections:
        objects: car
    motion:
      threshold: 50
      contour_area: 10
      improve_contrast: 'true'

    review:
      detections:
        required_zones: detection
objects:
  track:
    - person
    - car

detectors:
  deepstack:
    api_url: http://192.168.0.14:5000/v1/vision/detection
#    type: deepstack
    api_timeout: 3.1

version: 0.14
```
