### ISSUE TITLE
Codeproject.ai region parameter

### ISSUE THREAD

**Issue by federicotravaini** [ljmerza/frigate_plate_recognizer#78]
Hi, is it possible to configure a region parameter when using codeproject ai? The same way we do it with plate_recognizer

```
plate_recognizer:
  api_url: http://HOST-IP:8080/v1/plate-reader
  token: xxxxxxxxxx
  regions:
    - us-ca
```

But like this

```
code_project:
  api_url: http://127.0.0.1:32168/v1/image/alpr
  regions:
    - us-ca
```
